### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by martoio** [NornV/prj-rev-bwfs-dasmoto#3]
You could have placed all of the CSS into this block: https://github.com/NornV/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L10

Given your HTML, you only have one h1, so it would make sense to place all of the code there. Otherwise it implies that your page has more than one h1 tags.

(Best practice tip): To be completely semantic I would do something like this:

```
in HTML:
<header>
    <h1>Dasmoto's Arts &amp; Crafts</h1>
</header>
//======//
in CSS:
header{
    background: url(...url goes here)...;
}

header h1{
    font-size: 100px;
    font-weight: bold;
    color: khaki;
    text-align: center;
}
```

Why do it this way? You create a ``<header>`` (semantic HTML) which you attach the background to and then inside that you put your ``<h1>`` which contains only the text. Otherwise you use the h1 to add both text AND a background image. Good enough for this project, but if you start working on larger projects, it can quickly become inflexible. That being said, you can also argue that using only an h1 leads to less elements and potentially less complexity. It's up to you to decide which method you prefer and be able to justify using it.

**Comment by NornV** [comment]
Thanks for the detailed feedback -- it's very helpful to my learning!
